create table USERS
(
  OBJECT_ID           NUMBER,
  PASSWORD     VARCHAR2(100),
  FIRSTNAME    VARCHAR2(100),
  LASTNAME     VARCHAR2(100),
  EMAIL        VARCHAR2(100),
  ENABLED      NUMBER,
  PHONE_NUMBER  VARCHAR2(50),
  AUTHORITY_ID NUMBER
);