ALTER TABLE "USER"
  ADD (
  CONSTRAINT user_pk PRIMARY KEY (ID),
  CONSTRAINT user_id_not_null CHECK (ID IS NOT NULL),
  CONSTRAINT user_authority_id_fk FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY (ID));