INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (22, 1, 'BOEING 737');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (22, 2, 'AIRBUS A320');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (22, 3, 'BOEING 777');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (22, 4, 'AIRBUS A350');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (22, 5, 'BOEING 747');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (22, 6, 'AIRBUS A380');