DELETE FROM NC_AIRPORT.LISTS;

INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 1, 'ROLE_ADMIN');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 2, 'ROLE_USER');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 3, 'ROLE_CASHIER');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 4, 'ROLE_ANALYST');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 5, 'ROLE_CONTROLLER');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (33, 6, 'BOUGHT');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (33, 7, 'ARCHIVED');
