DELETE FROM NC_AIRPORT.LISTS;

INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 1, 'ROLE_ADMIN');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 2, 'ROLE_USER');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 3, 'ROLE_CASHIER');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 4, 'ROLE_ANALYST');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (49, 5, 'ROLE_CONTROLLER');

INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (33, 6, 'NEW');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (33, 7, 'BOUGHT');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (33, 8, 'ARCHIVED');

INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (63, 9, 'SCHEDULED');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (63, 10, 'CHECK_IN');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (63, 11, 'BOARDING');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (63, 12, 'DEPARTED');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (63, 13, 'EXPECTED');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (63, 14, 'LANDED');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (63, 15, 'DELAYED');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (63, 16, 'CANCELED');
INSERT INTO NC_AIRPORT.LISTS (ATTR_ID, LIST_VALUE_ID, VALUE) VALUES (63, 17, 'REDIRECTED');
