DELETE FROM NC_AIRPORT.OBJTYPE;

INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (1, null, 'COUNTRY', 'Country', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (2, null, 'AIRPORT', 'Airport', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (3, null, 'FLIGHT', 'Flight', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (4, null, 'AIRLINE', 'Airline', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (5, null, 'AIRPLANE', 'Airplane', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (6, null, 'EXTRA', 'Extra', NULL);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (7, null, 'EXTRA_TYPE', 'Extra type', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (8, null, 'SEAT', 'Seat', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (9, null, 'SEAT_TYPE', 'Seat type', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (10, null, 'TICKET', 'Ticket', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (11, null, 'TICKET_HAS_EXTRA', 'Ticket has extra', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (13, null, 'PASSENGER', 'Passenger', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (14, null, 'PASSPORT', 'Passport', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (15, null, 'USER', 'User', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (16, null, 'CREDIT_CARD', 'Credit card', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (18, null, 'TICKET_HISTORY', 'Ticket history', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (19, null, 'CITY', 'City', null);
