DELETE FROM NC_AIRPORT.OBJTYPE;

INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (1, null, 'COUNTRY', 'COUNTRY', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (2, null, 'AIRPORT', 'AIRPORT', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (3, null, 'FLIGHT', 'FLIGHT', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (4, null, 'AIRLINE', 'AIRLINE', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (5, null, 'AIRPLANE', 'AIRPLANE', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (6, null, 'EXTRA', 'EXTRA', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (7, null, 'EXTRA_TYPE', 'EXTRA_TYPE', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (8, null, 'SEAT', 'SEAT', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (9, null, 'SEAT_TYPE', 'SEAT_TYPE', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (10, null, 'TICKET', 'TICKET', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (11, null, 'TICKET_HAS_EXTRA', 'TICKET_HAS_EXTRA', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (13, null, 'PASSENGER', 'PASSENGER', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (14, null, 'PASSPORT', 'PASSPORT', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (15, null, 'USER', 'USER', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (16, null, 'CREDIT_CARD', 'CREDIT_CARD', null);
INSERT INTO NC_AIRPORT.OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (18, null, 'TICKET_HISTORY', 'TICKET_HISTORY', null);
